# We want to run this on Ubuntu 18.04 LTS
dist: bionic

language: java

sudo: required

services:
  - docker

jobs:
  include:
    - name: "JDK 8"
      jdk: openjdk8
      env: MVN_BUILD_SCRIPT="clean verify"
    - name: "JDK 11 with Sonar analysis"
      jdk: openjdk11
      env: MVN_BUILD_SCRIPT="-Pcoverage clean verify sonar:sonar -Dsonar.projectKey=AxonFramework_extension-amqp"

before_install:
  - docker run -d -p 4369:4369 -p 5671:5671 -p 5672:5672 rabbitmq
  - docker ps

install: true

cache:
  directories:
    - $HOME/.m2

# We switch JDK by setting the JAVA_HOME environment variable. All JDKs are under the same base directory.
script:
  - mvn -version
  - mvn -B -U $MVN_BUILD_SCRIPT

notifications:
  slack:
    secure: d1HN9GBeH0e6EsHjNkPVXgBaFCYqbvjkZv9GUkpWnyjNYP5V1snSk6sO4X6ONttydgzfbElZTOfrgDzRTgWJ76iDMxAPccFPY7dmGcpw8/2TOjwP6H6yEitiiZcWR9fssTM2Li2WQtuGkwaVBhw15JNABzEsexxqXC+Cu48yUfA=

addons:
  sonarcloud:
    organization: "axonframework"
    token:
      secure: "J8BMThZOf0rWz2Evrux2HvPW7TOMdjJCyJudIIHKTU/y9RJHz8LNUqO+/Tx+ySD27eyv91OtWW3J2N8OwcVM0JC335m2vZ7OJZEKi0nDTi+AmkqQ41QWAEMEbnrb8SNn1yWS6x7p6fRMe3roSlWcHRC8/Mp3SfdWTesuyusUQg5bPl+RaOQjXTacV4W3e1sQStusOLEJjD1aINzef7t3juzcGob+FSCySJDQ663gB9urWps41cMVHReGfWEnro/7xYu2WdxjVLUFlOPKfxpummJpx00+m6I2+iM15H6664NBlvp/3me3jXiXcO1Moz7+WfIbHL/ahICr4dYhKHqvbEI44e2+swBrmunVheNii/uvNJG9g7Sb0ThMIJhR5YnHbMsu0GppeApKbds5pcyt9ttWRPfq6SzZJCTFYGd3JnqOesCdfZTzxZuu+QZF8ZZH3/6aUaGjErR4eBecmmSVcWxdHZR6kyLx7ALx8f6szKCOQZss2RHOQD+1Stlmzvyc9TwHd7TdPaJOzu1zn6lQTvxKnlXZ38telEFZxxE5PmQaCQ6rWGehd4RX1d1GCVmdDSJ53v6IbDqhBeZMSOr2MOCDcFs0YVRTkSoh/s7tShxXmxN4Zb+ryGXYvF3O3reZuFnB/D1UGQtC88e2lK1Eua56VCUT4U6F5Ojx2vY1K4Y="