version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"
