= Major Releases

This page notes all enhancements and features that we have introduced to our major releases of the Axon AMQP Extension.

[#_release_4_9]
== Release 4.9

Release 4.9.0 only consists out of dependency upgrades to tag along with recent developments.

[#_release_4_8]
== Release 4.8

Release 4.8.0 only consists out of dependency upgrades to tag along with recent developments.

[#_release_4_7]
== Release 4.7

=== Enhancements

- Add support for Spring boot 3. link:https://github.com/AxonFramework/extension-amqp/pull/320[#320]

=== Contributors

We'd like to thank all the contributors who worked on this release:

- link:https://github.com/gklijs[@gklijs]

[#_release_4_6]
== Release 4.6

If you're curious about the dependency upgrades made in this release we refer to link:https://github.com/AxonFramework/extension-amqp/releases/tag/axon-amqp-4.6.0[this] page.

=== Enhancements

- Change how Sonar is invoked for GHAs link:https://github.com/AxonFramework/extension-amqp/pull/162[#162]
- Added an AMQP sample to show how to use the extension link:https://github.com/AxonFramework/extension-amqp/pull/126[#126]
- Splitted builds into pr and not pr, added ghactions to Dependabot and other minors link:https://github.com/AxonFramework/extension-amqp/pull/88[#88]

=== Bugfixes

- Precision on Date Time Utils link:https://github.com/AxonFramework/extension-amqp/issues/94[#94]

=== Contributors

We'd like to thank all the contributors who worked on this release:

- link:https://github.com/smcvb[@smcvb]
- link:https://github.com/lfgcampos[@lfgcampos]

[#_release_4_5]
== Release 4.5

* Issue link:https://github.com/AxonFramework/extension-amqp/pull/5[#5] introduces Dependabot.
This updated a large amount of the versions used by this extension.

* We updated all tests to a more current testing solution.
This means we introduced link:https://www.testcontainers.org/[Testcontainers] and updated JUnit to version 5.
You can find the made changes in link:https://github.com/AxonFramework/extension-amqp/pull/44[this] pull request.

You can check link:https://github.com/AxonFramework/extension-amqp/releases/tag/axon-amqp-4.5[this] page for a complete list of all changes.

[#_release_4_4]
== Release 4.4

* Issue link:https://github.com/AxonFramework/extension-amqp/pull/3[#3] introduces support for Spring Boot Developer Tools.

* We introduce Dependabot, which updated the log4j version.

[#_release_4_3]
== Release 4.3

We did not introduce any significant changes other than updating the extension to use Axon Framework release 4.3.

[#_release_4_2]
== Release 4.2

We did not introduce any significant changes other than updating the extension to use Axon Framework release 4.2.

[#_release_4_1]
== Release 4.1

A version predicament caused the extension to load the wrong package for the `ChannelAwareMessageListener`.
We resolved this issue for release 4.1 link:https://github.com/AxonFramework/extension-amqp/issues/1[here].

Furthermore, we updated the dependency on Axon Framework to 4.1.

[#_release_4_0]
== Release 4.0

We split off the AMQP logic from Axon Framework core into a dedicated repository.
Next to that, it complies with Axon Framework's 4.0 release.
